<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>ManufacturingDataApp</RootNamespace>
    <OptionStrict>On</OptionStrict><OptionExplicit>On</OptionExplicit><OptionInfer>On</OptionInfer>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ManufacturingDataApp.Application\ManufacturingDataApp.Application.vbproj" />
    <ProjectReference Include="..\ManufacturingDataApp.Infrastructure\ManufacturingDataApp.Infrastructure.vbproj" />
    <ProjectReference Include="..\ManufacturingDataApp.Domain\ManufacturingDataApp.Domain.vbproj" />
  </ItemGroup>
</Project>
